final List<String> Categories = ['Electronics', 'Personal items', 'Animals'];
final List<String> Cities = [
  "Riyadh",
  "Jeddah",
  "Mecca",
  "Medina",
  "Ad Dammām",
  "Al Hufūf",
  "Buraydah",
  "Al Ḩillah",
  "Aţ Ţa’if",
  "Tabuk",
  "Khamis Mushayţ",
  "Ha’il",
  "Al Qaţīf",
  "Al Mubarraz",
  "Al Kharj",
  "Najrān",
  "Yanbu‘",
  "Abhā",
  "Arar",
  "Jāzān",
  "Sakākā",
  "Al Bāḩah",
];
